/**
 * Logo Tiger SQL Helper - Schema Loader
 * JSON dosyalarindan tablo semalarini yukler ve yonetir
 */

import schema from '@/data/schema.json';

// Tablo JSON dosyalarini dinamik olarak import et
const tableModules = {
  'LG_NET_XXX': () => import('@/data/tables/LG_NET_XXX.json'),
  'LG_XXX_ABUDGETPRD': () => import('@/data/tables/LG_XXX_ABUDGETPRD.json'),
  'LG_XXX_ACCCODES': () => import('@/data/tables/LG_XXX_ACCCODES.json'),
  'LG_XXX_ACCCRREL': () => import('@/data/tables/LG_XXX_ACCCRREL.json'),
  'LG_XXX_ACCDISTTEMP': () => import('@/data/tables/LG_XXX_ACCDISTTEMP.json'),
  'LG_XXX_ACCDISTTEMPLN': () => import('@/data/tables/LG_XXX_ACCDISTTEMPLN.json'),
  'LG_XXX_ACCOUNTTEMPLATES': () => import('@/data/tables/LG_XXX_ACCOUNTTEMPLATES.json'),
  'LG_XXX_ACTIVITYAMNT': () => import('@/data/tables/LG_XXX_ACTIVITYAMNT.json'),
  'LG_XXX_ACTOVRHDDIST': () => import('@/data/tables/LG_XXX_ACTOVRHDDIST.json'),
  'LG_XXX_ADDTAX': () => import('@/data/tables/LG_XXX_ADDTAX.json'),
  'LG_XXX_ADDTAXLINE': () => import('@/data/tables/LG_XXX_ADDTAXLINE.json'),
  'LG_XXX_ANBUDGET': () => import('@/data/tables/LG_XXX_ANBUDGET.json'),
  'LG_XXX_ANBUDGETLN': () => import('@/data/tables/LG_XXX_ANBUDGETLN.json'),
  'LG_XXX_ANBUDGETPRD': () => import('@/data/tables/LG_XXX_ANBUDGETPRD.json'),
  'LG_XXX_APPPARAM': () => import('@/data/tables/LG_XXX_APPPARAM.json'),
  'LG_XXX_APPROVEUSER': () => import('@/data/tables/LG_XXX_APPROVEUSER.json'),
  'LG_XXX_ASCOND': () => import('@/data/tables/LG_XXX_ASCOND.json'),
  'LG_XXX_AUTOCTEMPLATE': () => import('@/data/tables/LG_XXX_AUTOCTEMPLATE.json'),
  'LG_XXX_AVGCURRS': () => import('@/data/tables/LG_XXX_AVGCURRS.json'),
  'LG_XXX_BANKACC': () => import('@/data/tables/LG_XXX_BANKACC.json'),
  'LG_XXX_BARCODETMP': () => import('@/data/tables/LG_XXX_BARCODETMP.json'),
  'LG_XXX_BNCARD': () => import('@/data/tables/LG_XXX_BNCARD.json'),
  'LG_XXX_BNCREDITCARD': () => import('@/data/tables/LG_XXX_BNCREDITCARD.json'),
  'LG_XXX_BNCREPAYTR': () => import('@/data/tables/LG_XXX_BNCREPAYTR.json'),
  'LG_XXX_BOMASTER': () => import('@/data/tables/LG_XXX_BOMASTER.json'),
  'LG_XXX_BOMLINE': () => import('@/data/tables/LG_XXX_BOMLINE.json'),
  'LG_XXX_BOMPARAM': () => import('@/data/tables/LG_XXX_BOMPARAM.json'),
  'LG_XXX_BOMREVSN': () => import('@/data/tables/LG_XXX_BOMREVSN.json'),
  'LG_XXX_BOMVRNTFORMULA': () => import('@/data/tables/LG_XXX_BOMVRNTFORMULA.json'),
  'LG_XXX_CAMPAIGN': () => import('@/data/tables/LG_XXX_CAMPAIGN.json'),
  'LG_XXX_CASHFLOWDEF': () => import('@/data/tables/LG_XXX_CASHFLOWDEF.json'),
  'LG_XXX_CHANGELOG': () => import('@/data/tables/LG_XXX_CHANGELOG.json'),
  'LG_XXX_CHARASGN': () => import('@/data/tables/LG_XXX_CHARASGN.json'),
  'LG_XXX_CHARCODE': () => import('@/data/tables/LG_XXX_CHARCODE.json'),
  'LG_XXX_CHARSET': () => import('@/data/tables/LG_XXX_CHARSET.json'),
  'LG_XXX_CHARSETASGN': () => import('@/data/tables/LG_XXX_CHARSETASGN.json'),
  'LG_XXX_CHARVAL': () => import('@/data/tables/LG_XXX_CHARVAL.json'),
  'LG_XXX_CLCARD': () => import('@/data/tables/LG_XXX_CLCARD.json'),
  'LG_XXX_CLINTEL': () => import('@/data/tables/LG_XXX_CLINTEL.json'),
  'LG_XXX_CMPGNLINE': () => import('@/data/tables/LG_XXX_CMPGNLINE.json'),
  'LG_XXX_COMPANSEACC': () => import('@/data/tables/LG_XXX_COMPANSEACC.json'),
  'LG_XXX_COPRDBOM': () => import('@/data/tables/LG_XXX_COPRDBOM.json'),
  'LG_XXX_CRDACREF': () => import('@/data/tables/LG_XXX_CRDACREF.json'),
  'LG_XXX_CREDITLETTERS': () => import('@/data/tables/LG_XXX_CREDITLETTERS.json'),
  'LG_XXX_DECARDS': () => import('@/data/tables/LG_XXX_DECARDS.json'),
  'LG_XXX_DEDUCTLIMITS': () => import('@/data/tables/LG_XXX_DEDUCTLIMITS.json'),
  'LG_XXX_DEFNFLDSCARDV': () => import('@/data/tables/LG_XXX_DEFNFLDSCARDV.json'),
  'LG_XXX_DISCPAYLINES': () => import('@/data/tables/LG_XXX_DISCPAYLINES.json'),
  'LG_XXX_DISPLINE': () => import('@/data/tables/LG_XXX_DISPLINE.json'),
  'LG_XXX_DISPLINECOST': () => import('@/data/tables/LG_XXX_DISPLINECOST.json'),
  'LG_XXX_DISTLINE': () => import('@/data/tables/LG_XXX_DISTLINE.json'),
  'LG_XXX_DISTLIST': () => import('@/data/tables/LG_XXX_DISTLIST.json'),
  'LG_XXX_DISTROUTING': () => import('@/data/tables/LG_XXX_DISTROUTING.json'),
  'LG_XXX_DISTROUTLINE': () => import('@/data/tables/LG_XXX_DISTROUTLINE.json'),
  'LG_XXX_DISTTEMP': () => import('@/data/tables/LG_XXX_DISTTEMP.json'),
  'LG_XXX_DISTVEHICLE': () => import('@/data/tables/LG_XXX_DISTVEHICLE.json'),
  'LG_XXX_DIVAMAIN': () => import('@/data/tables/LG_XXX_DIVAMAIN.json'),
  'LG_XXX_DSPLNOPCMPPG': () => import('@/data/tables/LG_XXX_DSPLNOPCMPPG.json'),
  'LG_XXX_EBOOKINFO': () => import('@/data/tables/LG_XXX_EBOOKINFO.json'),
  'LG_XXX_EBOOKPARAMS': () => import('@/data/tables/LG_XXX_EBOOKPARAMS.json'),
  'LG_XXX_EMCENTER': () => import('@/data/tables/LG_XXX_EMCENTER.json'),
  'LG_XXX_EMGRPASS': () => import('@/data/tables/LG_XXX_EMGRPASS.json'),
  'LG_XXX_EMPGROUP': () => import('@/data/tables/LG_XXX_EMPGROUP.json'),
  'LG_XXX_EMPLOYEE': () => import('@/data/tables/LG_XXX_EMPLOYEE.json'),
  'LG_XXX_EMUHACC': () => import('@/data/tables/LG_XXX_EMUHACC.json'),
  'LG_XXX_EMUHACCSUBACCASGN': () => import('@/data/tables/LG_XXX_EMUHACCSUBACCASGN.json'),
  'LG_XXX_ENGCLINE': () => import('@/data/tables/LG_XXX_ENGCLINE.json'),
  'LG_XXX_EXCEPT': () => import('@/data/tables/LG_XXX_EXCEPT.json'),
  'LG_XXX_EXIMBUSTYP': () => import('@/data/tables/LG_XXX_EXIMBUSTYP.json'),
  'LG_XXX_EXPCREDITCRD': () => import('@/data/tables/LG_XXX_EXPCREDITCRD.json'),
  'LG_XXX_EXPCREDITLN': () => import('@/data/tables/LG_XXX_EXPCREDITLN.json'),
  'LG_XXX_FAANNCOST': () => import('@/data/tables/LG_XXX_FAANNCOST.json'),
  'LG_XXX_FAEXPENSE': () => import('@/data/tables/LG_XXX_FAEXPENSE.json'),
  'LG_XXX_FAPRODNUMS': () => import('@/data/tables/LG_XXX_FAPRODNUMS.json'),
  'LG_XXX_FAREGIST': () => import('@/data/tables/LG_XXX_FAREGIST.json'),
  'LG_XXX_FAREGNEWVALUE': () => import('@/data/tables/LG_XXX_FAREGNEWVALUE.json'),
  'LG_XXX_FATRANS': () => import('@/data/tables/LG_XXX_FATRANS.json'),
  'LG_XXX_FAYEAR': () => import('@/data/tables/LG_XXX_FAYEAR.json'),
  'LG_XXX_FAYEARSTOP': () => import('@/data/tables/LG_XXX_FAYEARSTOP.json'),
  'LG_XXX_FICHESTATUS': () => import('@/data/tables/LG_XXX_FICHESTATUS.json'),
  'LG_XXX_FINTABLEITEM': () => import('@/data/tables/LG_XXX_FINTABLEITEM.json'),
  'LG_XXX_FINTBLHEADER': () => import('@/data/tables/LG_XXX_FINTBLHEADER.json'),
  'LG_XXX_FINTBLLINEACC': () => import('@/data/tables/LG_XXX_FINTBLLINEACC.json'),
  'LG_XXX_FIRMDOC': () => import('@/data/tables/LG_XXX_FIRMDOC.json'),
  'LG_XXX_FORECASTHEAD': () => import('@/data/tables/LG_XXX_FORECASTHEAD.json'),
  'LG_XXX_FORECASTLINE': () => import('@/data/tables/LG_XXX_FORECASTLINE.json'),
  'LG_XXX_FRMPRDPARAM': () => import('@/data/tables/LG_XXX_FRMPRDPARAM.json'),
  'LG_XXX_GAUGPARAM': () => import('@/data/tables/LG_XXX_GAUGPARAM.json'),
  'LG_XXX_GENMODP': () => import('@/data/tables/LG_XXX_GENMODP.json'),
  'LG_XXX_GERMANYDEF': () => import('@/data/tables/LG_XXX_GERMANYDEF.json'),
  'LG_XXX_GLASSGN': () => import('@/data/tables/LG_XXX_GLASSGN.json'),
  'LG_XXX_GLCONNFILT': () => import('@/data/tables/LG_XXX_GLCONNFILT.json'),
  'LG_XXX_GUARANTEELINE': () => import('@/data/tables/LG_XXX_GUARANTEELINE.json'),
  'LG_XXX_HISTORY': () => import('@/data/tables/LG_XXX_HISTORY.json'),
  'LG_XXX_INVDEF': () => import('@/data/tables/LG_XXX_INVDEF.json'),
  'LG_XXX_ITEMCATEGORY': () => import('@/data/tables/LG_XXX_ITEMCATEGORY.json'),
  'LG_XXX_ITEMCATEGORYLINE': () => import('@/data/tables/LG_XXX_ITEMCATEGORYLINE.json'),
  'LG_XXX_ITEMOBTAINLIMIT': () => import('@/data/tables/LG_XXX_ITEMOBTAINLIMIT.json'),
  'LG_XXX_ITEMS': () => import('@/data/tables/LG_XXX_ITEMS.json'),
  'LG_XXX_ITEMSUBS': () => import('@/data/tables/LG_XXX_ITEMSUBS.json'),
  'LG_XXX_ITMBOMAS': () => import('@/data/tables/LG_XXX_ITMBOMAS.json'),
  'LG_XXX_ITMCLSAS': () => import('@/data/tables/LG_XXX_ITMCLSAS.json'),
  'LG_XXX_ITMFACTP': () => import('@/data/tables/LG_XXX_ITMFACTP.json'),
  'LG_XXX_ITMLVLTMP': () => import('@/data/tables/LG_XXX_ITMLVLTMP.json'),
  'LG_XXX_ITMLVLTMPLN': () => import('@/data/tables/LG_XXX_ITMLVLTMPLN.json'),
  'LG_XXX_ITMUNITA': () => import('@/data/tables/LG_XXX_ITMUNITA.json'),
  'LG_XXX_ITMWSDEF': () => import('@/data/tables/LG_XXX_ITMWSDEF.json'),
  'LG_XXX_ITMWSTOT': () => import('@/data/tables/LG_XXX_ITMWSTOT.json'),
  'LG_XXX_KSCARD': () => import('@/data/tables/LG_XXX_KSCARD.json'),
  'LG_XXX_LABORREQ': () => import('@/data/tables/LG_XXX_LABORREQ.json'),
  'LG_XXX_LEASINGPAYMENTS': () => import('@/data/tables/LG_XXX_LEASINGPAYMENTS.json'),
  'LG_XXX_LEASINGPAYMENTSLNS': () => import('@/data/tables/LG_XXX_LEASINGPAYMENTSLNS.json'),
  'LG_XXX_LEASINGREG': () => import('@/data/tables/LG_XXX_LEASINGREG.json'),
  'LG_XXX_LEASINGREGLN': () => import('@/data/tables/LG_XXX_LEASINGREGLN.json'),
  'LG_XXX_LNGEXCSETS': () => import('@/data/tables/LG_XXX_LNGEXCSETS.json'),
  'LG_XXX_LNOPASGN': () => import('@/data/tables/LG_XXX_LNOPASGN.json'),
  'LG_XXX_LOCATION': () => import('@/data/tables/LG_XXX_LOCATION.json'),
  'LG_XXX_LOCATIONSFOR': () => import('@/data/tables/LG_XXX_LOCATIONSFOR.json'),
  'LG_XXX_LOGREP': () => import('@/data/tables/LG_XXX_LOGREP.json'),
  'LG_XXX_MAINTANENCELINE': () => import('@/data/tables/LG_XXX_MAINTANENCELINE.json'),
  'LG_XXX_MARK': () => import('@/data/tables/LG_XXX_MARK.json'),
  'LG_XXX_MARKET': () => import('@/data/tables/LG_XXX_MARKET.json'),
  'LG_XXX_MARKETPLACE': () => import('@/data/tables/LG_XXX_MARKETPLACE.json'),
  'LG_XXX_MBLINFOGROUP': () => import('@/data/tables/LG_XXX_MBLINFOGROUP.json'),
  'LG_XXX_MBLINFOUSER': () => import('@/data/tables/LG_XXX_MBLINFOUSER.json'),
  'LG_XXX_MBLINFUSRGRPLN': () => import('@/data/tables/LG_XXX_MBLINFUSRGRPLN.json'),
  'LG_XXX_MBSCRMRELF': () => import('@/data/tables/LG_XXX_MBSCRMRELF.json'),
  'LG_XXX_MNTDEMANDFICHE': () => import('@/data/tables/LG_XXX_MNTDEMANDFICHE.json'),
  'LG_XXX_MNTDEMANDLINE': () => import('@/data/tables/LG_XXX_MNTDEMANDLINE.json'),
  'LG_XXX_MNTLIFEHIST': () => import('@/data/tables/LG_XXX_MNTLIFEHIST.json'),
  'LG_XXX_MNTORDERFICHE': () => import('@/data/tables/LG_XXX_MNTORDERFICHE.json'),
  'LG_XXX_MNTORDERLINE': () => import('@/data/tables/LG_XXX_MNTORDERLINE.json'),
  'LG_XXX_MNTTEMPLATE': () => import('@/data/tables/LG_XXX_MNTTEMPLATE.json'),
  'LG_XXX_MNTTEMPLATEASGN': () => import('@/data/tables/LG_XXX_MNTTEMPLATEASGN.json'),
  'LG_XXX_MNTTEMPLATELINE': () => import('@/data/tables/LG_XXX_MNTTEMPLATELINE.json'),
  'LG_XXX_MOBILEASSET': () => import('@/data/tables/LG_XXX_MOBILEASSET.json'),
  'LG_XXX_MOLDREQ': () => import('@/data/tables/LG_XXX_MOLDREQ.json'),
  'LG_XXX_MRPHEAD': () => import('@/data/tables/LG_XXX_MRPHEAD.json'),
  'LG_XXX_MRPITEM': () => import('@/data/tables/LG_XXX_MRPITEM.json'),
  'LG_XXX_MRPITEMCHG': () => import('@/data/tables/LG_XXX_MRPITEMCHG.json'),
  'LG_XXX_MRPLINE': () => import('@/data/tables/LG_XXX_MRPLINE.json'),
  'LG_XXX_MRPPEGGING': () => import('@/data/tables/LG_XXX_MRPPEGGING.json'),
  'LG_XXX_MRPPROPOSAL': () => import('@/data/tables/LG_XXX_MRPPROPOSAL.json'),
  'LG_XXX_MSGTEMPLATE': () => import('@/data/tables/LG_XXX_MSGTEMPLATE.json'),
  'LG_XXX_MULTIADDTAX': () => import('@/data/tables/LG_XXX_MULTIADDTAX.json'),
  'LG_XXX_NMMSGTEMPLATE': () => import('@/data/tables/LG_XXX_NMMSGTEMPLATE.json'),
  'LG_XXX_OCCUPATION': () => import('@/data/tables/LG_XXX_OCCUPATION.json'),
  'LG_XXX_OCCUPATN': () => import('@/data/tables/LG_XXX_OCCUPATN.json'),
  'LG_XXX_OFFFCEXCH': () => import('@/data/tables/LG_XXX_OFFFCEXCH.json'),
  'LG_XXX_OFFLINEEXCH': () => import('@/data/tables/LG_XXX_OFFLINEEXCH.json'),
  'LG_XXX_OPATTASG': () => import('@/data/tables/LG_XXX_OPATTASG.json'),
  'LG_XXX_OPERTION': () => import('@/data/tables/LG_XXX_OPERTION.json'),
  'LG_XXX_OPREQACTIVITY': () => import('@/data/tables/LG_XXX_OPREQACTIVITY.json'),
  'LG_XXX_OPRTREQ': () => import('@/data/tables/LG_XXX_OPRTREQ.json'),
  'LG_XXX_OVERHEADS': () => import('@/data/tables/LG_XXX_OVERHEADS.json'),
  'LG_XXX_OVHCDISTRATE': () => import('@/data/tables/LG_XXX_OVHCDISTRATE.json'),
  'LG_XXX_OVHDTRANS': () => import('@/data/tables/LG_XXX_OVHDTRANS.json'),
  'LG_XXX_OVRHDACCREF': () => import('@/data/tables/LG_XXX_OVRHDACCREF.json'),
  'LG_XXX_OVRHDCENTER': () => import('@/data/tables/LG_XXX_OVRHDCENTER.json'),
  'LG_XXX_OVRHDCENTERLN': () => import('@/data/tables/LG_XXX_OVRHDCENTERLN.json'),
  'LG_XXX_PARAMASGN': () => import('@/data/tables/LG_XXX_PARAMASGN.json'),
  'LG_XXX_PAYLINES': () => import('@/data/tables/LG_XXX_PAYLINES.json'),
  'LG_XXX_PAYPLANS': () => import('@/data/tables/LG_XXX_PAYPLANS.json'),
  'LG_XXX_PEGGING': () => import('@/data/tables/LG_XXX_PEGGING.json'),
  'LG_XXX_PERFTEST': () => import('@/data/tables/LG_XXX_PERFTEST.json'),
  'LG_XXX_POACCREF': () => import('@/data/tables/LG_XXX_POACCREF.json'),
  'LG_XXX_POLINE': () => import('@/data/tables/LG_XXX_POLINE.json'),
  'LG_XXX_PRCARDS': () => import('@/data/tables/LG_XXX_PRCARDS.json'),
  'LG_XXX_PRCLIST': () => import('@/data/tables/LG_XXX_PRCLIST.json'),
  'LG_XXX_PRCLSTDIV': () => import('@/data/tables/LG_XXX_PRCLSTDIV.json'),
  'LG_XXX_PREVDISPLINE': () => import('@/data/tables/LG_XXX_PREVDISPLINE.json'),
  'LG_XXX_PRINTLIMITS': () => import('@/data/tables/LG_XXX_PRINTLIMITS.json'),
  'LG_XXX_PRODORD': () => import('@/data/tables/LG_XXX_PRODORD.json'),
  'LG_XXX_PRODUCERPARAMS': () => import('@/data/tables/LG_XXX_PRODUCERPARAMS.json'),
  'LG_XXX_PRODUCTLINE': () => import('@/data/tables/LG_XXX_PRODUCTLINE.json'),
  'LG_XXX_PROJECT': () => import('@/data/tables/LG_XXX_PROJECT.json'),
  'LG_XXX_PRVOPASG': () => import('@/data/tables/LG_XXX_PRVOPASG.json'),
  'LG_XXX_PTSNOTICE': () => import('@/data/tables/LG_XXX_PTSNOTICE.json'),
  'LG_XXX_PURCHOFFER': () => import('@/data/tables/LG_XXX_PURCHOFFER.json'),
  'LG_XXX_PURCHOFFERLN': () => import('@/data/tables/LG_XXX_PURCHOFFERLN.json'),
  'LG_XXX_QASGN': () => import('@/data/tables/LG_XXX_QASGN.json'),
  'LG_XXX_QCLVAL': () => import('@/data/tables/LG_XXX_QCLVAL.json'),
  'LG_XXX_QCSET': () => import('@/data/tables/LG_XXX_QCSET.json'),
  'LG_XXX_QCSLINE': () => import('@/data/tables/LG_XXX_QCSLINE.json'),
  'LG_XXX_QCTRANSFERPARAM': () => import('@/data/tables/LG_XXX_QCTRANSFERPARAM.json'),
  'LG_XXX_RECKEEPING': () => import('@/data/tables/LG_XXX_RECKEEPING.json'),
  'LG_XXX_REFLECT': () => import('@/data/tables/LG_XXX_REFLECT.json'),
  'LG_XXX_REFLECTTRANS': () => import('@/data/tables/LG_XXX_REFLECTTRANS.json'),
  'LG_XXX_RELATEDDOCS': () => import('@/data/tables/LG_XXX_RELATEDDOCS.json'),
  'LG_XXX_REPAYPLAN': () => import('@/data/tables/LG_XXX_REPAYPLAN.json'),
  'LG_XXX_REPAYPLANS': () => import('@/data/tables/LG_XXX_REPAYPLANS.json'),
  'LG_XXX_REPAYPLANSLN': () => import('@/data/tables/LG_XXX_REPAYPLANSLN.json'),
  'LG_XXX_REPQUEUE': () => import('@/data/tables/LG_XXX_REPQUEUE.json'),
  'LG_XXX_RETTAXPEGG': () => import('@/data/tables/LG_XXX_RETTAXPEGG.json'),
  'LG_XXX_ROFMMAIN': () => import('@/data/tables/LG_XXX_ROFMMAIN.json'),
  'LG_XXX_ROFMSUB': () => import('@/data/tables/LG_XXX_ROFMSUB.json'),
  'LG_XXX_ROUTE': () => import('@/data/tables/LG_XXX_ROUTE.json'),
  'LG_XXX_ROUTETRS': () => import('@/data/tables/LG_XXX_ROUTETRS.json'),
  'LG_XXX_ROUTING': () => import('@/data/tables/LG_XXX_ROUTING.json'),
  'LG_XXX_RTNGLINE': () => import('@/data/tables/LG_XXX_RTNGLINE.json'),
  'LG_XXX_SECTORMAIN': () => import('@/data/tables/LG_XXX_SECTORMAIN.json'),
  'LG_XXX_SECTORSUB': () => import('@/data/tables/LG_XXX_SECTORSUB.json'),
  'LG_XXX_SELCHVAL': () => import('@/data/tables/LG_XXX_SELCHVAL.json'),
  'LG_XXX_SHFTASGN': () => import('@/data/tables/LG_XXX_SHFTASGN.json'),
  'LG_XXX_SHFTTIME': () => import('@/data/tables/LG_XXX_SHFTTIME.json'),
  'LG_XXX_SHIFT': () => import('@/data/tables/LG_XXX_SHIFT.json'),
  'LG_XXX_SHIPINFO': () => import('@/data/tables/LG_XXX_SHIPINFO.json'),
  'LG_XXX_SLSCLREL': () => import('@/data/tables/LG_XXX_SLSCLREL.json'),
  'LG_XXX_SLSMAN': () => import('@/data/tables/LG_XXX_SLSMAN.json'),
  'LG_XXX_SPECODES': () => import('@/data/tables/LG_XXX_SPECODES.json'),
  'LG_XXX_SPEVALLNSCORE': () => import('@/data/tables/LG_XXX_SPEVALLNSCORE.json'),
  'LG_XXX_SRVCARD': () => import('@/data/tables/LG_XXX_SRVCARD.json'),
  'LG_XXX_SRVUNITA': () => import('@/data/tables/LG_XXX_SRVUNITA.json'),
  'LG_XXX_STCOMPLN': () => import('@/data/tables/LG_XXX_STCOMPLN.json'),
  'LG_XXX_STDBOMCOST': () => import('@/data/tables/LG_XXX_STDBOMCOST.json'),
  'LG_XXX_STDCOST': () => import('@/data/tables/LG_XXX_STDCOST.json'),
  'LG_XXX_STDCOSTPERIOD': () => import('@/data/tables/LG_XXX_STDCOSTPERIOD.json'),
  'LG_XXX_STDUNITCOST': () => import('@/data/tables/LG_XXX_STDUNITCOST.json'),
  'LG_XXX_STOPASGN': () => import('@/data/tables/LG_XXX_STOPASGN.json'),
  'LG_XXX_STOPCAUSE': () => import('@/data/tables/LG_XXX_STOPCAUSE.json'),
  'LG_XXX_STOPTRANS': () => import('@/data/tables/LG_XXX_STOPTRANS.json'),
  'LG_XXX_SUPPASGN': () => import('@/data/tables/LG_XXX_SUPPASGN.json'),
  'LG_XXX_SUPPCRSET': () => import('@/data/tables/LG_XXX_SUPPCRSET.json'),
  'LG_XXX_SUPPCRSETLN': () => import('@/data/tables/LG_XXX_SUPPCRSETLN.json'),
  'LG_XXX_SUPPCRSETSUB': () => import('@/data/tables/LG_XXX_SUPPCRSETSUB.json'),
  'LG_XXX_SUPPEVALCR': () => import('@/data/tables/LG_XXX_SUPPEVALCR.json'),
  'LG_XXX_SUPPEVALCRLN': () => import('@/data/tables/LG_XXX_SUPPEVALCRLN.json'),
  'LG_XXX_SUPPEVALFICHE': () => import('@/data/tables/LG_XXX_SUPPEVALFICHE.json'),
  'LG_XXX_SUPPEVALTRANS': () => import('@/data/tables/LG_XXX_SUPPEVALTRANS.json'),
  'LG_XXX_SUPPEVALTRSET': () => import('@/data/tables/LG_XXX_SUPPEVALTRSET.json'),
  'LG_XXX_SUPPEVALTRSUB': () => import('@/data/tables/LG_XXX_SUPPEVALTRSUB.json'),
  'LG_XXX_TARGETS': () => import('@/data/tables/LG_XXX_TARGETS.json'),
  'LG_XXX_TAXDECLHDR': () => import('@/data/tables/LG_XXX_TAXDECLHDR.json'),
  'LG_XXX_TAXDECLLINE': () => import('@/data/tables/LG_XXX_TAXDECLLINE.json'),
  'LG_XXX_TAXDECLLINEACC': () => import('@/data/tables/LG_XXX_TAXDECLLINEACC.json'),
  'LG_XXX_TOOLREQ': () => import('@/data/tables/LG_XXX_TOOLREQ.json'),
  'LG_XXX_TRADGRPAYPLANCON': () => import('@/data/tables/LG_XXX_TRADGRPAYPLANCON.json'),
  'LG_XXX_TRGPAR': () => import('@/data/tables/LG_XXX_TRGPAR.json'),
  'LG_XXX_TSKSHELN': () => import('@/data/tables/LG_XXX_TSKSHELN.json'),
  'LG_XXX_UCOSTCONTROL': () => import('@/data/tables/LG_XXX_UCOSTCONTROL.json'),
  'LG_XXX_UNITBARCODE': () => import('@/data/tables/LG_XXX_UNITBARCODE.json'),
  'LG_XXX_UNITSETC': () => import('@/data/tables/LG_XXX_UNITSETC.json'),
  'LG_XXX_UNITSETF': () => import('@/data/tables/LG_XXX_UNITSETF.json'),
  'LG_XXX_UNITSETL': () => import('@/data/tables/LG_XXX_UNITSETL.json'),
  'LG_XXX_UTILINVMTCH': () => import('@/data/tables/LG_XXX_UTILINVMTCH.json'),
  'LG_XXX_UTILINVMTCHLN': () => import('@/data/tables/LG_XXX_UTILINVMTCHLN.json'),
  'LG_XXX_VARIANT': () => import('@/data/tables/LG_XXX_VARIANT.json'),
  'LG_XXX_VEHICLECLSHIP': () => import('@/data/tables/LG_XXX_VEHICLECLSHIP.json'),
  'LG_XXX_VEHICLEWHOUSE': () => import('@/data/tables/LG_XXX_VEHICLEWHOUSE.json'),
  'LG_XXX_VRNTCHARASGN': () => import('@/data/tables/LG_XXX_VRNTCHARASGN.json'),
  'LG_XXX_VRNTGENERICINF': () => import('@/data/tables/LG_XXX_VRNTGENERICINF.json'),
  'LG_XXX_WFLOWROLE': () => import('@/data/tables/LG_XXX_WFLOWROLE.json'),
  'LG_XXX_WFLOWROLELN': () => import('@/data/tables/LG_XXX_WFLOWROLELN.json'),
  'LG_XXX_WFTASK': () => import('@/data/tables/LG_XXX_WFTASK.json'),
  'LG_XXX_WFTASKPER': () => import('@/data/tables/LG_XXX_WFTASKPER.json'),
  'LG_XXX_WHLIST': () => import('@/data/tables/LG_XXX_WHLIST.json'),
  'LG_XXX_WORKDAY': () => import('@/data/tables/LG_XXX_WORKDAY.json'),
  'LG_XXX_WORKFLOWCARD': () => import('@/data/tables/LG_XXX_WORKFLOWCARD.json'),
  'LG_XXX_WORKFLOWLINE': () => import('@/data/tables/LG_XXX_WORKFLOWLINE.json'),
  'LG_XXX_WORKSTAT': () => import('@/data/tables/LG_XXX_WORKSTAT.json'),
  'LG_XXX_WSATTASG': () => import('@/data/tables/LG_XXX_WSATTASG.json'),
  'LG_XXX_WSATTVAS': () => import('@/data/tables/LG_XXX_WSATTVAS.json'),
  'LG_XXX_WSCHCODE': () => import('@/data/tables/LG_XXX_WSCHCODE.json'),
  'LG_XXX_WSCHVAL': () => import('@/data/tables/LG_XXX_WSCHVAL.json'),
  'LG_XXX_WSGRPASS': () => import('@/data/tables/LG_XXX_WSGRPASS.json'),
  'LG_XXX_WSGRPF': () => import('@/data/tables/LG_XXX_WSGRPF.json'),
  'LG_XXX_WSOVHCASGN': () => import('@/data/tables/LG_XXX_WSOVHCASGN.json'),
  'LG_XXX_WSTATPART': () => import('@/data/tables/LG_XXX_WSTATPART.json'),
  'LG_XXX_XX_ACCDISTDETLN': () => import('@/data/tables/LG_XXX_XX_ACCDISTDETLN.json'),
  'LG_XXX_XX_ACCFCASGN': () => import('@/data/tables/LG_XXX_XX_ACCFCASGN.json'),
  'LG_XXX_XX_ANBDGTALLOCFC': () => import('@/data/tables/LG_XXX_XX_ANBDGTALLOCFC.json'),
  'LG_XXX_XX_ANBDGTALLOCLN': () => import('@/data/tables/LG_XXX_XX_ANBDGTALLOCLN.json'),
  'LG_XXX_XX_ANBDGTALLOCPRD': () => import('@/data/tables/LG_XXX_XX_ANBDGTALLOCPRD.json'),
  'LG_XXX_XX_ANBDGTREVFC': () => import('@/data/tables/LG_XXX_XX_ANBDGTREVFC.json'),
  'LG_XXX_XX_ANBDGTREVLN': () => import('@/data/tables/LG_XXX_XX_ANBDGTREVLN.json'),
  'LG_XXX_XX_ANBDGTREVPRD': () => import('@/data/tables/LG_XXX_XX_ANBDGTREVPRD.json'),
  'LG_XXX_XX_APPROVAL': () => import('@/data/tables/LG_XXX_XX_APPROVAL.json'),
  'LG_XXX_XX_APPROVE': () => import('@/data/tables/LG_XXX_XX_APPROVE.json'),
  'LG_XXX_XX_APPROVERS': () => import('@/data/tables/LG_XXX_XX_APPROVERS.json'),
  'LG_XXX_XX_BNFICHE': () => import('@/data/tables/LG_XXX_XX_BNFICHE.json'),
  'LG_XXX_XX_BNFLINE': () => import('@/data/tables/LG_XXX_XX_BNFLINE.json'),
  'LG_XXX_XX_BNTOTFIL': () => import('@/data/tables/LG_XXX_XX_BNTOTFIL.json'),
  'LG_XXX_XX_CASHFLOWCARD': () => import('@/data/tables/LG_XXX_XX_CASHFLOWCARD.json'),
  'LG_XXX_XX_CASHFLOWLINE': () => import('@/data/tables/LG_XXX_XX_CASHFLOWLINE.json'),
  'LG_XXX_XX_CLBRANCHPAYPLANS': () => import('@/data/tables/LG_XXX_XX_CLBRANCHPAYPLANS.json'),
  'LG_XXX_XX_CLCOLLATRLRISK': () => import('@/data/tables/LG_XXX_XX_CLCOLLATRLRISK.json'),
  'LG_XXX_XX_CLFICHE': () => import('@/data/tables/LG_XXX_XX_CLFICHE.json'),
  'LG_XXX_XX_CLFLINE': () => import('@/data/tables/LG_XXX_XX_CLFLINE.json'),
  'LG_XXX_XX_CLPARAMHEADER': () => import('@/data/tables/LG_XXX_XX_CLPARAMHEADER.json'),
  'LG_XXX_XX_CLPARAMS': () => import('@/data/tables/LG_XXX_XX_CLPARAMS.json'),
  'LG_XXX_XX_CLRNUMS': () => import('@/data/tables/LG_XXX_XX_CLRNUMS.json'),
  'LG_XXX_XX_CLTOTFIL': () => import('@/data/tables/LG_XXX_XX_CLTOTFIL.json'),
  'LG_XXX_XX_COLLATRLCARD': () => import('@/data/tables/LG_XXX_XX_COLLATRLCARD.json'),
  'LG_XXX_XX_COLLATRLROLL': () => import('@/data/tables/LG_XXX_XX_COLLATRLROLL.json'),
  'LG_XXX_XX_COLLATRLTRAN': () => import('@/data/tables/LG_XXX_XX_COLLATRLTRAN.json'),
  'LG_XXX_XX_COLLCOMMPAYTR': () => import('@/data/tables/LG_XXX_XX_COLLCOMMPAYTR.json'),
  'LG_XXX_XX_COSTDISTFC': () => import('@/data/tables/LG_XXX_XX_COSTDISTFC.json'),
  'LG_XXX_XX_COSTDISTLN': () => import('@/data/tables/LG_XXX_XX_COSTDISTLN.json'),
  'LG_XXX_XX_COSTDISTPEG': () => import('@/data/tables/LG_XXX_XX_COSTDISTPEG.json'),
  'LG_XXX_XX_CSCARD': () => import('@/data/tables/LG_XXX_XX_CSCARD.json'),
  'LG_XXX_XX_CSHTOTS': () => import('@/data/tables/LG_XXX_XX_CSHTOTS.json'),
  'LG_XXX_XX_CSPAYMENT': () => import('@/data/tables/LG_XXX_XX_CSPAYMENT.json'),
  'LG_XXX_XX_CSROLL': () => import('@/data/tables/LG_XXX_XX_CSROLL.json'),
  'LG_XXX_XX_CSTRANS': () => import('@/data/tables/LG_XXX_XX_CSTRANS.json'),
  'LG_XXX_XX_DATAEXCHHISTORY': () => import('@/data/tables/LG_XXX_XX_DATAEXCHHISTORY.json'),
  'LG_XXX_XX_DEFNFLDSTRANV': () => import('@/data/tables/LG_XXX_XX_DEFNFLDSTRANV.json'),
  'LG_XXX_XX_DEMANDFICHE': () => import('@/data/tables/LG_XXX_XX_DEMANDFICHE.json'),
  'LG_XXX_XX_DEMANDLINE': () => import('@/data/tables/LG_XXX_XX_DEMANDLINE.json'),
  'LG_XXX_XX_DEMANDPEGGING': () => import('@/data/tables/LG_XXX_XX_DEMANDPEGGING.json'),
  'LG_XXX_XX_DIIB': () => import('@/data/tables/LG_XXX_XX_DIIB.json'),
  'LG_XXX_XX_DIIBBOMLINE': () => import('@/data/tables/LG_XXX_XX_DIIBBOMLINE.json'),
  'LG_XXX_XX_DIIBLINE': () => import('@/data/tables/LG_XXX_XX_DIIBLINE.json'),
  'LG_XXX_XX_DISCPAYTRANS': () => import('@/data/tables/LG_XXX_XX_DISCPAYTRANS.json'),
  'LG_XXX_XX_DISTORD': () => import('@/data/tables/LG_XXX_XX_DISTORD.json'),
  'LG_XXX_XX_DISTORDLINE': () => import('@/data/tables/LG_XXX_XX_DISTORDLINE.json'),
  'LG_XXX_XX_DIVATRANS': () => import('@/data/tables/LG_XXX_XX_DIVATRANS.json'),
  'LG_XXX_XX_DOCPRINT': () => import('@/data/tables/LG_XXX_XX_DOCPRINT.json'),
  'LG_XXX_XX_DOCSCHEMA': () => import('@/data/tables/LG_XXX_XX_DOCSCHEMA.json'),
  'LG_XXX_XX_DOCSELLIST': () => import('@/data/tables/LG_XXX_XX_DOCSELLIST.json'),
  'LG_XXX_XX_EARCHIVEDET': () => import('@/data/tables/LG_XXX_XX_EARCHIVEDET.json'),
  'LG_XXX_XX_EBOOKDETAILDOC': () => import('@/data/tables/LG_XXX_XX_EBOOKDETAILDOC.json'),
  'LG_XXX_XX_EINVOICEDET': () => import('@/data/tables/LG_XXX_XX_EINVOICEDET.json'),
  'LG_XXX_XX_EINVOICELOG': () => import('@/data/tables/LG_XXX_XX_EINVOICELOG.json'),
  'LG_XXX_XX_EMDEMDETLN': () => import('@/data/tables/LG_XXX_XX_EMDEMDETLN.json'),
  'LG_XXX_XX_EMDEMFICHE': () => import('@/data/tables/LG_XXX_XX_EMDEMFICHE.json'),
  'LG_XXX_XX_EMDEMFLINE': () => import('@/data/tables/LG_XXX_XX_EMDEMFLINE.json'),
  'LG_XXX_XX_EMFICHE': () => import('@/data/tables/LG_XXX_XX_EMFICHE.json'),
  'LG_XXX_XX_EMFLINE': () => import('@/data/tables/LG_XXX_XX_EMFLINE.json'),
  'LG_XXX_XX_EMFLNINFCOEF': () => import('@/data/tables/LG_XXX_XX_EMFLNINFCOEF.json'),
  'LG_XXX_XX_EMUHTOT': () => import('@/data/tables/LG_XXX_XX_EMUHTOT.json'),
  'LG_XXX_XX_EPRODUCERRECDET': () => import('@/data/tables/LG_XXX_XX_EPRODUCERRECDET.json'),
  'LG_XXX_XX_ETRADESMANINVDET': () => import('@/data/tables/LG_XXX_XX_ETRADESMANINVDET.json'),
  'LG_XXX_XX_EXCDIFFTRANS': () => import('@/data/tables/LG_XXX_XX_EXCDIFFTRANS.json'),
  'LG_XXX_XX_EXIMDISTFC': () => import('@/data/tables/LG_XXX_XX_EXIMDISTFC.json'),
  'LG_XXX_XX_EXIMDISTLN': () => import('@/data/tables/LG_XXX_XX_EXIMDISTLN.json'),
  'LG_XXX_XX_EXIMDISTPEG': () => import('@/data/tables/LG_XXX_XX_EXIMDISTPEG.json'),
  'LG_XXX_XX_EXIMHISTORY': () => import('@/data/tables/LG_XXX_XX_EXIMHISTORY.json'),
  'LG_XXX_XX_EXIMWHFC': () => import('@/data/tables/LG_XXX_XX_EXIMWHFC.json'),
  'LG_XXX_XX_EXIMWHTRANS': () => import('@/data/tables/LG_XXX_XX_EXIMWHTRANS.json'),
  'LG_XXX_XX_EXTRAINFO': () => import('@/data/tables/LG_XXX_XX_EXTRAINFO.json'),
  'LG_XXX_XX_FCACCREF': () => import('@/data/tables/LG_XXX_XX_FCACCREF.json'),
  'LG_XXX_XX_FICHEOBJECT': () => import('@/data/tables/LG_XXX_XX_FICHEOBJECT.json'),
  'LG_XXX_XX_FOLDER': () => import('@/data/tables/LG_XXX_XX_FOLDER.json'),
  'LG_XXX_XX_GIBACCFICHE': () => import('@/data/tables/LG_XXX_XX_GIBACCFICHE.json'),
  'LG_XXX_XX_GIBACCFICHELN': () => import('@/data/tables/LG_XXX_XX_GIBACCFICHELN.json'),
  'LG_XXX_XX_GNTOTBN': () => import('@/data/tables/LG_XXX_XX_GNTOTBN.json'),
  'LG_XXX_XX_GNTOTCL': () => import('@/data/tables/LG_XXX_XX_GNTOTCL.json'),
  'LG_XXX_XX_GNTOTCSH': () => import('@/data/tables/LG_XXX_XX_GNTOTCSH.json'),
  'LG_XXX_XX_GNTOTST': () => import('@/data/tables/LG_XXX_XX_GNTOTST.json'),
  'LG_XXX_XX_GNTOTVRNT': () => import('@/data/tables/LG_XXX_XX_GNTOTVRNT.json'),
  'LG_XXX_XX_GUARANTOR': () => import('@/data/tables/LG_XXX_XX_GUARANTOR.json'),
  'LG_XXX_XX_HISTORY': () => import('@/data/tables/LG_XXX_XX_HISTORY.json'),
  'LG_XXX_XX_IMPSRVREL': () => import('@/data/tables/LG_XXX_XX_IMPSRVREL.json'),
  'LG_XXX_XX_INSTALCARD': () => import('@/data/tables/LG_XXX_XX_INSTALCARD.json'),
  'LG_XXX_XX_INVENVAL': () => import('@/data/tables/LG_XXX_XX_INVENVAL.json'),
  'LG_XXX_XX_INVENVALLN': () => import('@/data/tables/LG_XXX_XX_INVENVALLN.json'),
  'LG_XXX_XX_INVEXIMINFO': () => import('@/data/tables/LG_XXX_XX_INVEXIMINFO.json'),
  'LG_XXX_XX_INVEXIMLINES': () => import('@/data/tables/LG_XXX_XX_INVEXIMLINES.json'),
  'LG_XXX_XX_INVOICE': () => import('@/data/tables/LG_XXX_XX_INVOICE.json'),
  'LG_XXX_XX_INVOICEEXCH': () => import('@/data/tables/LG_XXX_XX_INVOICEEXCH.json'),
  'LG_XXX_XX_INVOICEINTEL': () => import('@/data/tables/LG_XXX_XX_INVOICEINTEL.json'),
  'LG_XXX_XX_ITMWSTOT': () => import('@/data/tables/LG_XXX_XX_ITMWSTOT.json'),
  'LG_XXX_XX_JOURNAL': () => import('@/data/tables/LG_XXX_XX_JOURNAL.json'),
  'LG_XXX_XX_KSDISTDETLINES': () => import('@/data/tables/LG_XXX_XX_KSDISTDETLINES.json'),
  'LG_XXX_XX_KSLINES': () => import('@/data/tables/LG_XXX_XX_KSLINES.json'),
  'LG_XXX_XX_LABELS': () => import('@/data/tables/LG_XXX_XX_LABELS.json'),
  'LG_XXX_XX_LDXRECDELREQ': () => import('@/data/tables/LG_XXX_XX_LDXRECDELREQ.json'),
  'LG_XXX_XX_MBSCRMRELP': () => import('@/data/tables/LG_XXX_XX_MBSCRMRELP.json'),
  'LG_XXX_XX_MULTIADDTAXLN': () => import('@/data/tables/LG_XXX_XX_MULTIADDTAXLN.json'),
  'LG_XXX_XX_OKCINFO': () => import('@/data/tables/LG_XXX_XX_OKCINFO.json'),
  'LG_XXX_XX_ORDCMFINTRANS': () => import('@/data/tables/LG_XXX_XX_ORDCMFINTRANS.json'),
  'LG_XXX_XX_ORDCMPRICE': () => import('@/data/tables/LG_XXX_XX_ORDCMPRICE.json'),
  'LG_XXX_XX_ORDFEXCH': () => import('@/data/tables/LG_XXX_XX_ORDFEXCH.json'),
  'LG_XXX_XX_ORDLINEEXCH': () => import('@/data/tables/LG_XXX_XX_ORDLINEEXCH.json'),
  'LG_XXX_XX_ORDPEGGING': () => import('@/data/tables/LG_XXX_XX_ORDPEGGING.json'),
  'LG_XXX_XX_ORFICHE': () => import('@/data/tables/LG_XXX_XX_ORFICHE.json'),
  'LG_XXX_XX_ORFLINE': () => import('@/data/tables/LG_XXX_XX_ORFLINE.json'),
  'LG_XXX_XX_PACKAGEASGN': () => import('@/data/tables/LG_XXX_XX_PACKAGEASGN.json'),
  'LG_XXX_XX_PACKAGEFCLN': () => import('@/data/tables/LG_XXX_XX_PACKAGEFCLN.json'),
  'LG_XXX_XX_PACKAGEFICHE': () => import('@/data/tables/LG_XXX_XX_PACKAGEFICHE.json'),
  'LG_XXX_XX_PAYTRANS': () => import('@/data/tables/LG_XXX_XX_PAYTRANS.json'),
  'LG_XXX_XX_PERDOC': () => import('@/data/tables/LG_XXX_XX_PERDOC.json'),
  'LG_XXX_XX_PLUGINS': () => import('@/data/tables/LG_XXX_XX_PLUGINS.json'),
  'LG_XXX_XX_PRDCOST': () => import('@/data/tables/LG_XXX_XX_PRDCOST.json'),
  'LG_XXX_XX_PREACCDISTDETLINE': () => import('@/data/tables/LG_XXX_XX_PREACCDISTDETLINE.json'),
  'LG_XXX_XX_PROCESSLOG': () => import('@/data/tables/LG_XXX_XX_PROCESSLOG.json'),
  'LG_XXX_XX_PROCUREMENT': () => import('@/data/tables/LG_XXX_XX_PROCUREMENT.json'),
  'LG_XXX_XX_PRODUCER': () => import('@/data/tables/LG_XXX_XX_PRODUCER.json'),
  'LG_XXX_XX_QPRODLINE': () => import('@/data/tables/LG_XXX_XX_QPRODLINE.json'),
  'LG_XXX_XX_QPRODUCT': () => import('@/data/tables/LG_XXX_XX_QPRODUCT.json'),
  'LG_XXX_XX_RECKEEPING': () => import('@/data/tables/LG_XXX_XX_RECKEEPING.json'),
  'LG_XXX_XX_REFLECTASGN': () => import('@/data/tables/LG_XXX_XX_REFLECTASGN.json'),
  'LG_XXX_XX_REMINDHIST': () => import('@/data/tables/LG_XXX_XX_REMINDHIST.json'),
  'LG_XXX_XX_RESPONSEHISTORY': () => import('@/data/tables/LG_XXX_XX_RESPONSEHISTORY.json'),
  'LG_XXX_XX_RULEHISTORY': () => import('@/data/tables/LG_XXX_XX_RULEHISTORY.json'),
  'LG_XXX_XX_RULES': () => import('@/data/tables/LG_XXX_XX_RULES.json'),
  'LG_XXX_XX_SERILOTN': () => import('@/data/tables/LG_XXX_XX_SERILOTN.json'),
  'LG_XXX_XX_SLQCASGN': () => import('@/data/tables/LG_XXX_XX_SLQCASGN.json'),
  'LG_XXX_XX_SLTRANS': () => import('@/data/tables/LG_XXX_XX_SLTRANS.json'),
  'LG_XXX_XX_SPECTEMPLATES': () => import('@/data/tables/LG_XXX_XX_SPECTEMPLATES.json'),
  'LG_XXX_XX_SRVNUMS': () => import('@/data/tables/LG_XXX_XX_SRVNUMS.json'),
  'LG_XXX_XX_SRVTOT': () => import('@/data/tables/LG_XXX_XX_SRVTOT.json'),
  'LG_XXX_XX_STFCEXTINF': () => import('@/data/tables/LG_XXX_XX_STFCEXTINF.json'),
  'LG_XXX_XX_STFEXCH': () => import('@/data/tables/LG_XXX_XX_STFEXCH.json'),
  'LG_XXX_XX_STFICHE': () => import('@/data/tables/LG_XXX_XX_STFICHE.json'),
  'LG_XXX_XX_STINVENS': () => import('@/data/tables/LG_XXX_XX_STINVENS.json'),
  'LG_XXX_XX_STINVTOT': () => import('@/data/tables/LG_XXX_XX_STINVTOT.json'),
  'LG_XXX_XX_STLINE': () => import('@/data/tables/LG_XXX_XX_STLINE.json'),
  'LG_XXX_XX_STLINECOST': () => import('@/data/tables/LG_XXX_XX_STLINECOST.json'),
  'LG_XXX_XX_STLINEEXCH': () => import('@/data/tables/LG_XXX_XX_STLINEEXCH.json'),
  'LG_XXX_XX_STLNINFCOEF': () => import('@/data/tables/LG_XXX_XX_STLNINFCOEF.json'),
  'LG_XXX_XX_STLNIOPEGGING': () => import('@/data/tables/LG_XXX_XX_STLNIOPEGGING.json'),
  'LG_XXX_XX_STSHIPPEDAMOUNT': () => import('@/data/tables/LG_XXX_XX_STSHIPPEDAMOUNT.json'),
  'LG_XXX_XX_TMPACASGN': () => import('@/data/tables/LG_XXX_XX_TMPACASGN.json'),
  'LG_XXX_XX_TRANSAC': () => import('@/data/tables/LG_XXX_XX_TRANSAC.json'),
  'LG_XXX_XX_UETDSCARGOINFO': () => import('@/data/tables/LG_XXX_XX_UETDSCARGOINFO.json'),
  'LG_XXX_XX_UETDSVOYAGE': () => import('@/data/tables/LG_XXX_XX_UETDSVOYAGE.json'),
  'LG_XXX_XX_VRNTINVENS': () => import('@/data/tables/LG_XXX_XX_VRNTINVENS.json'),
  'LG_XXX_XX_VRNTINVTOT': () => import('@/data/tables/LG_XXX_XX_VRNTINVTOT.json'),
  // Program-independent LG_ tables (no firm number)
  'LG_ACTPEPL': () => import('@/data/tables/LG_ACTPEPL.json'),
  'LG_CATEGLISTS': () => import('@/data/tables/LG_CATEGLISTS.json'),
  'LG_CNTSLSMASG': () => import('@/data/tables/LG_CNTSLSMASG.json'),
  'LG_CONTACTS': () => import('@/data/tables/LG_CONTACTS.json'),
  'LG_CONTSPECDAYS': () => import('@/data/tables/LG_CONTSPECDAYS.json'),
  'LG_CSTVND': () => import('@/data/tables/LG_CSTVND.json'),
  'LG_CVARPASG': () => import('@/data/tables/LG_CVARPASG.json'),
  'LG_CVINDASG': () => import('@/data/tables/LG_CVINDASG.json'),
  'LG_EXCHANGE': () => import('@/data/tables/LG_EXCHANGE.json'),
  'LG_FIRMDOC': () => import('@/data/tables/LG_FIRMDOC.json'),
  'LG_HISTORY': () => import('@/data/tables/LG_HISTORY.json'),
  'LG_INDUSTRY': () => import('@/data/tables/LG_INDUSTRY.json'),
  'LG_NTLCK': () => import('@/data/tables/LG_NTLCK.json'),
  'LG_SATI': () => import('@/data/tables/LG_SATI.json'),
  'LG_SATIFILTER': () => import('@/data/tables/LG_SATIFILTER.json'),
  'LG_SLSACTIV': () => import('@/data/tables/LG_SLSACTIV.json'),
  'LG_SLSCLREL': () => import('@/data/tables/LG_SLSCLREL.json'),
  'LG_SLSDOC': () => import('@/data/tables/LG_SLSDOC.json'),
  'LG_SLSFILES': () => import('@/data/tables/LG_SLSFILES.json'),
  'LG_SLSMAN': () => import('@/data/tables/LG_SLSMAN.json'),
  'LG_SLSOHISTORY': () => import('@/data/tables/LG_SLSOHISTORY.json'),
  'LG_SLSOPPOR': () => import('@/data/tables/LG_SLSOPPOR.json'),
  'LG_USAGESTAT': () => import('@/data/tables/LG_USAGESTAT.json'),
  // Log tables
  'LOGRPFLT': () => import('@/data/tables/LOGRPFLT.json'),
  'LOGRPLAYS': () => import('@/data/tables/LOGRPLAYS.json'),
  // Program-independent L_ tables (system tables)
  'L_ADLOGS': () => import('@/data/tables/L_ADLOGS.json'),
  'L_BANKCODE': () => import('@/data/tables/L_BANKCODE.json'),
  'L_BNBRANCH': () => import('@/data/tables/L_BNBRANCH.json'),
  'L_BRWSSTAT': () => import('@/data/tables/L_BRWSSTAT.json'),
  'L_CAPIDEF': () => import('@/data/tables/L_CAPIDEF.json'),
  'L_CAPIDEPT': () => import('@/data/tables/L_CAPIDEPT.json'),
  'L_CAPIDIV': () => import('@/data/tables/L_CAPIDIV.json'),
  'L_CAPIDMCONN': () => import('@/data/tables/L_CAPIDMCONN.json'),
  'L_CAPIDO': () => import('@/data/tables/L_CAPIDO.json'),
  'L_CAPIDOC': () => import('@/data/tables/L_CAPIDOC.json'),
  'L_CAPIDRIGHT': () => import('@/data/tables/L_CAPIDRIGHT.json'),
  'L_CAPIESHOP': () => import('@/data/tables/L_CAPIESHOP.json'),
  'L_CAPIEXTINFO': () => import('@/data/tables/L_CAPIEXTINFO.json'),
  'L_CAPIFACTDIV': () => import('@/data/tables/L_CAPIFACTDIV.json'),
  'L_CAPIFACTORY': () => import('@/data/tables/L_CAPIFACTORY.json'),
  'L_CAPIFIRM': () => import('@/data/tables/L_CAPIFIRM.json'),
  'L_CAPIGROUP': () => import('@/data/tables/L_CAPIGROUP.json'),
  'L_CAPIPERIOD': () => import('@/data/tables/L_CAPIPERIOD.json'),
  'L_CAPIPROG': () => import('@/data/tables/L_CAPIPROG.json'),
  'L_CAPIRIGHT': () => import('@/data/tables/L_CAPIRIGHT.json'),
  'L_CAPIROLE': () => import('@/data/tables/L_CAPIROLE.json'),
  'L_CAPIROLEOBJ': () => import('@/data/tables/L_CAPIROLEOBJ.json'),
  'L_CAPIROLETASK': () => import('@/data/tables/L_CAPIROLETASK.json'),
  'L_CAPISIGN': () => import('@/data/tables/L_CAPISIGN.json'),
  'L_CAPISITE': () => import('@/data/tables/L_CAPISITE.json'),
  'L_CAPITERMINAL': () => import('@/data/tables/L_CAPITERMINAL.json'),
  'L_CAPIUNIT': () => import('@/data/tables/L_CAPIUNIT.json'),
  'L_CAPIUPDATE': () => import('@/data/tables/L_CAPIUPDATE.json'),
  'L_CAPIUSER': () => import('@/data/tables/L_CAPIUSER.json'),
  'L_CAPIVERS': () => import('@/data/tables/L_CAPIVERS.json'),
  'L_CAPIWEBCONN': () => import('@/data/tables/L_CAPIWEBCONN.json'),
  'L_CAPIWHOUSE': () => import('@/data/tables/L_CAPIWHOUSE.json'),
  'L_CDBTMP': () => import('@/data/tables/L_CDBTMP.json'),
  'L_CITY': () => import('@/data/tables/L_CITY.json'),
  'L_CONSCODES': () => import('@/data/tables/L_CONSCODES.json'),
  'L_COUNTRY': () => import('@/data/tables/L_COUNTRY.json'),
  'L_CPA_CODE': () => import('@/data/tables/L_CPA_CODE.json'),
  'L_CPA_DEF': () => import('@/data/tables/L_CPA_DEF.json'),
  'L_CTYCODES': () => import('@/data/tables/L_CTYCODES.json'),
  'L_CURRENCYLIST': () => import('@/data/tables/L_CURRENCYLIST.json'),
  'L_CURRENCYPARS': () => import('@/data/tables/L_CURRENCYPARS.json'),
  'L_CUSTOM': () => import('@/data/tables/L_CUSTOM.json'),
  'L_DAILYEXCHANGES': () => import('@/data/tables/L_DAILYEXCHANGES.json'),
  'L_DEFNFLDSD': () => import('@/data/tables/L_DEFNFLDSD.json'),
  'L_DISTRICT': () => import('@/data/tables/L_DISTRICT.json'),
  'L_DRIVERS': () => import('@/data/tables/L_DRIVERS.json'),
  'L_DYNREP': () => import('@/data/tables/L_DYNREP.json'),
  'L_DYNREPUSRR': () => import('@/data/tables/L_DYNREPUSRR.json'),
  'L_EBUSINESS': () => import('@/data/tables/L_EBUSINESS.json'),
  'L_FACULTY': () => import('@/data/tables/L_FACULTY.json'),
  'L_FAREGEXPC': () => import('@/data/tables/L_FAREGEXPC.json'),
  'L_FAREGTYPES': () => import('@/data/tables/L_FAREGTYPES.json'),
  'L_FIRMPARAMS': () => import('@/data/tables/L_FIRMPARAMS.json'),
  'L_FREEZONE': () => import('@/data/tables/L_FREEZONE.json'),
  'L_FRGTYPES': () => import('@/data/tables/L_FRGTYPES.json'),
  'L_FRMOD': () => import('@/data/tables/L_FRMOD.json'),
  'L_GIBDOCLINETYPEREL': () => import('@/data/tables/L_GIBDOCLINETYPEREL.json'),
  'L_GIBDOCTYPE': () => import('@/data/tables/L_GIBDOCTYPE.json'),
  'L_GIBFAREGTYPE': () => import('@/data/tables/L_GIBFAREGTYPE.json'),
  'L_GIBLINERECTYPEREL': () => import('@/data/tables/L_GIBLINERECTYPEREL.json'),
  'L_GIBLINETYPE': () => import('@/data/tables/L_GIBLINETYPE.json'),
  'L_GIBLNSBRCTYPREL': () => import('@/data/tables/L_GIBLNSBRCTYPREL.json'),
  'L_GIBMMPARAM': () => import('@/data/tables/L_GIBMMPARAM.json'),
  'L_GIBOTHERPARAMS': () => import('@/data/tables/L_GIBOTHERPARAMS.json'),
  'L_GIBRECTYPE': () => import('@/data/tables/L_GIBRECTYPE.json'),
  'L_GIBSUBRECTYPE': () => import('@/data/tables/L_GIBSUBRECTYPE.json'),
  'L_GOUSERS': () => import('@/data/tables/L_GOUSERS.json'),
  'L_GTIP_CODE': () => import('@/data/tables/L_GTIP_CODE.json'),
  'L_GTIP_DEF': () => import('@/data/tables/L_GTIP_DEF.json'),
  'L_LBSLOADGRPRIGHTS': () => import('@/data/tables/L_LBSLOADGRPRIGHTS.json'),
  'L_LBSLOADUSRRIGHTS': () => import('@/data/tables/L_LBSLOADUSRRIGHTS.json'),
  'L_LDOCNUM': () => import('@/data/tables/L_LDOCNUM.json'),
  'L_LDOCNUM_2241TMP': () => import('@/data/tables/L_LDOCNUM_2241TMP.json'),
  'L_LNGEXCLS': () => import('@/data/tables/L_LNGEXCLS.json'),
  'L_LOG': () => import('@/data/tables/L_LOG.json'),
  'L_MANDFLDS': () => import('@/data/tables/L_MANDFLDS.json'),
  'L_MAPCONFIG': () => import('@/data/tables/L_MAPCONFIG.json'),
  'L_MDEVICES': () => import('@/data/tables/L_MDEVICES.json'),
  'L_MESSAGEATT': () => import('@/data/tables/L_MESSAGEATT.json'),
  'L_MESSAGES': () => import('@/data/tables/L_MESSAGES.json'),
  'L_NET': () => import('@/data/tables/L_NET.json'),
  'L_ORGDEFS': () => import('@/data/tables/L_ORGDEFS.json'),
  'L_ORGDOC': () => import('@/data/tables/L_ORGDOC.json'),
  'L_PAYTYPES': () => import('@/data/tables/L_PAYTYPES.json'),
  'L_PCKCODES': () => import('@/data/tables/L_PCKCODES.json'),
  'L_POSDEFS': () => import('@/data/tables/L_POSDEFS.json'),
  'L_POSTCODE': () => import('@/data/tables/L_POSTCODE.json'),
  'L_PRICEINDEX': () => import('@/data/tables/L_PRICEINDEX.json'),
  'L_PRICEINDEXTYP': () => import('@/data/tables/L_PRICEINDEXTYP.json'),
  'L_REDISCINTRATES': () => import('@/data/tables/L_REDISCINTRATES.json'),
  'L_REGIMETYP': () => import('@/data/tables/L_REGIMETYP.json'),
  'L_RPFILTS': () => import('@/data/tables/L_RPFILTS.json'),
  'L_RPFILTS001': () => import('@/data/tables/L_RPFILTS001.json'),
  'L_RPLAYS': () => import('@/data/tables/L_RPLAYS.json'),
  'L_RPLAYS_001': () => import('@/data/tables/L_RPLAYS_001.json'),
  'L_SCHOOL': () => import('@/data/tables/L_SCHOOL.json'),
  'L_SHPAGENT': () => import('@/data/tables/L_SHPAGENT.json'),
  'L_SHPTYPES': () => import('@/data/tables/L_SHPTYPES.json'),
  'L_SMS': () => import('@/data/tables/L_SMS.json'),
  'L_SMSUSER': () => import('@/data/tables/L_SMSUSER.json'),
  'L_STATUSINFO': () => import('@/data/tables/L_STATUSINFO.json'),
  'L_TABLELAYS': () => import('@/data/tables/L_TABLELAYS.json'),
  'L_TAXOFFICE': () => import('@/data/tables/L_TAXOFFICE.json'),
  'L_TEXTFAV': () => import('@/data/tables/L_TEXTFAV.json'),
  'L_TOWN': () => import('@/data/tables/L_TOWN.json'),
  'L_TRADGRP': () => import('@/data/tables/L_TRADGRP.json'),
  'L_TSCONT': () => import('@/data/tables/L_TSCONT.json'),
  'L_TSPROPS': () => import('@/data/tables/L_TSPROPS.json'),
  'L_USERBLOBTABLE': () => import('@/data/tables/L_USERBLOBTABLE.json'),
  'L_USERCOM': () => import('@/data/tables/L_USERCOM.json'),
  'L_USERSDEF': () => import('@/data/tables/L_USERSDEF.json'),
  'L_USERWINPREF': () => import('@/data/tables/L_USERWINPREF.json'),
  'L_WEBPAGE': () => import('@/data/tables/L_WEBPAGE.json'),
};

// Cache
let tablesCache = null;

/**
 * Tum kategorileri getirir
 * @returns {Array} Kategori listesi
 */
export function getCategories() {
  return schema.categories;
}

/**
 * Belirli bir kategoriyi getirir
 * @param {string} categoryId - Kategori ID
 * @returns {Object|null} Kategori objesi
 */
export function getCategoryById(categoryId) {
  return schema.categories.find(cat => cat.id === categoryId) || null;
}

/**
 * Placeholder bilgilerini getirir
 * @returns {Object} Placeholder tanimlari
 */
export function getPlaceholders() {
  return schema.placeholders;
}

/**
 * Mevcut tablo isimlerini getirir
 * @returns {Array} Tablo isimleri
 */
export function getAvailableTableNames() {
  return Object.keys(tableModules);
}

/**
 * Belirli bir tabloyu yukler
 * @param {string} tableName - Tablo adi (ornek: LG_XXX_CLCARD)
 * @returns {Promise<Object|null>} Tablo verisi
 */
export async function loadTable(tableName) {
  const loader = tableModules[tableName];
  if (!loader) {
    console.warn(`Tablo bulunamadi: ${tableName}`);
    return null;
  }

  try {
    const module = await loader();
    return module.default || module;
  } catch (error) {
    console.error(`Tablo yuklenirken hata: ${tableName}`, error);
    return null;
  }
}

/**
 * Tum tablolari yukler
 * @returns {Promise<Array>} Tum tablolar
 */
export async function loadAllTables() {
  if (tablesCache) {
    return tablesCache;
  }

  const tables = [];
  const tableNames = Object.keys(tableModules);

  for (const tableName of tableNames) {
    const table = await loadTable(tableName);
    if (table) {
      tables.push(table);
    }
  }

  tablesCache = tables;
  return tables;
}

/**
 * Kategoriye gore tablolari getirir
 * @param {string} categoryId - Kategori ID
 * @returns {Promise<Array>} Kategorideki tablolar
 */
export async function getTablesByCategory(categoryId) {
  const allTables = await loadAllTables();
  return allTables.filter(table => table.category === categoryId);
}

/**
 * Cache'i temizler
 */
export function clearCache() {
  tablesCache = null;
}

/**
 * Schema versiyonunu getirir
 * @returns {string} Versiyon
 */
export function getSchemaVersion() {
  return schema.version;
}

/**
 * Son guncelleme tarihini getirir
 * @returns {string} Tarih
 */
export function getLastUpdated() {
  return schema.lastUpdated;
}
